 update posts set base_title = '[마이크임팩트] 2018 서울 소셜 컨퍼런스' where id = 22999;
 update posts set base_title = '밸류가든 특강 요청' where id = 27061;
 update posts set base_title = '홈페이지 메인 1번 2번 3번 중 어떤게 마음에 드시나요?  @all 어떤 페이지로 구성하면 협업 문의가 많이 들어올까요?  댓글로 코멘트 부탁드려요.    * 목업에...' where id = 30398;
 update posts set base_title = '2019.09.26 운영팀 정기 회의록입니다. (첨부파일)' where id = 30705;
 update posts set base_title = '2019-10-16 베스툴 외부 회의록' where id = 31098;
 update posts set base_title = '2019.10.30 스탠드업 미팅' where id = 31182;
 update posts set base_title = '스프린트 1 ' where id = 31791;
 update posts set base_title = '스프린트 2.5' where id = 31859;
 update posts set base_title = '스프린트 2' where id = 31894;
 update posts set base_title = '스프린트 3' where id = 32025;
 update posts set base_title = '2020년 2월 20일 목요일 금귤 항해일지' where id = 32959;
 update posts set base_title = '테스트' where id = 34926;
 update posts set base_title = '체크인' where id = 34928;
 update posts set base_title = '테스트 ' where id = 34929;
 update posts set base_title = '글' where id = 34930;
 update posts set base_title = '페이징 테스트 1' where id = 34931;
 update posts set base_title = '페이징 테스트 2' where id = 34932;
 update posts set base_title = '페이징 테스트 3' where id = 34933;
 update posts set base_title = '페이징 테스트 4' where id = 34934;
 update posts set base_title = '페이징 테스트 5' where id = 34935;
 update posts set base_title = '페이징 테스트 6' where id = 34936;
 update posts set base_title = '페이징 테스트 7' where id = 34937;
 update posts set base_title = '페이징 테스트 8' where id = 34938;
 update posts set base_title = '페이징 테스트 9' where id = 34939;
 update posts set base_title = '도배 방지 위원회' where id = 34940;
 update posts set base_title = '[공지] 유스펀치 오거나이저를 찾습니다! 👀' where id = 34948;
 update posts set base_title = '[공지] 커뮤니티 멤버 이름을 공모합니다! ✍️' where id = 34949;
 update posts set base_title = '[인사] 첫 인사를 나눠보아요! 😁' where id = 34950;
 update posts set base_title = '[체크아웃🌈] 6월 둘째주 체크아웃' where id = 34951;
 update posts set base_title = '[체크인👋] 6월 둘째주 체크인' where id = 34952;
 update posts set base_title = '그룹스 3.0인가요?' where id = 34973;
 update posts set base_title = '쓰레기덕질 컵보증금제 축하파티' where id = 34985;
 update posts set base_title = '여름에 휴가는 어디로?' where id = 34986;
 update posts set base_title = '사진은 어떻게 올리는 걸까?' where id = 34987;
 update posts set base_title = '뉴그룹스 시작을 축하' where id = 34988;
 update posts set base_title = '테스트 ' where id = 34990;
 update posts set base_title = '📌그룹 주제 편집하고 나니 미분류 채널이 생성되었습니다.' where id = 34992;
 update posts set base_title = '행동강령' where id = 34993;
 update posts set base_title = '그룹스3.0 버그' where id = 34995;
 update posts set base_title = '빠띠에 오기 전' where id = 34996;
 update posts set base_title = '항해일지를 여기서 써보면?' where id = 35000;
 update posts set base_title = '글목록에 N의 공격!' where id = 35001;
 update posts set base_title = '3요소' where id = 35002;
 update posts set base_title = '목록으로 돌아가기 버튼' where id = 35003;
 update posts set base_title = '게시글 삭제가 되는지 확인용' where id = 35005;
 update posts set base_title = '에디터에서 새롭게 발견한 사실! ' where id = 35006;
 update posts set base_title = '저는 폴더도 만들어봤어요' where id = 35007;
 update posts set base_title = 'p.d.a' where id = 35008;
 update posts set base_title = '새친구 알람' where id = 35009;
 update posts set base_title = '달리님 회의의 시간입니다 회고' where id = 35010;
 update posts set base_title = '일감' where id = 35015;
 update posts set base_title = '그룹 멤버 전체에 알리는 글' where id = 35017;
 update posts set base_title = '댓글에도 새 댓글 표시 달기' where id = 35022;
 update posts set base_title = '그룹과 그룹 사이 거리' where id = 35028;
 update posts set base_title = '2020년 6월 16일 항해일지' where id = 35036;
 update posts set base_title = '잡담. 개발자 커뮤니티에서 로그(일지) 엿보기' where id = 35040;
 update posts set base_title = '모바일 3.0 목업' where id = 35047;
 update posts set base_title = '언젠가 게스트를...' where id = 35050;
 update posts set base_title = '글과 댓글의 게시시간에 대한 초간단 개선 의견' where id = 35055;
 update posts set base_title = '공지한 글을 확인하는 것' where id = 35060;
 update posts set base_title = '로그인 및 가입 만들기' where id = 35104;
 update posts set base_title = '유스펀치 2.0' where id = 35107;
 update posts set base_title = '6/18-19 항해일지 ' where id = 35111;
 update posts set base_title = '3.0의 폰트사이즈나 목록의 위아래 길이를 조금 줄여보면 어떨까요? ' where id = 35112;
 update posts set base_title = '에디터 내 enter 키를 눌렀을 경우 다음 줄 ' where id = 35113;
 update posts set base_title = '마지막에 접속한 채널을 기억하기' where id = 35125;
 update posts set base_title = '새 글을 주기적으로 확인하기' where id = 35127;
 update posts set base_title = '글 쓰기 테스트 1' where id = 35128;
 update posts set base_title = '사진, 파일 첨부 테스트' where id = 35129;
 update posts set base_title = '찬반투표 테스트' where id = 35130;
 update posts set base_title = '설문 테스트' where id = 35131;
 update posts set base_title = '그룹의 채널 개설 권한' where id = 35134;
 update posts set base_title = '레셈님과 디자인 관련 회의' where id = 35135;
 update posts set base_title = '대문위키에 들어가는 이미지 ' where id = 35136;
 update posts set base_title = '이미지 업로드 테스트 ' where id = 35137;
 update posts set base_title = '대문위키에 들어가는 이미지 디자인 ' where id = 35138;
 update posts set base_title = '3.0에서 공감을 누르고 싶었는데 댓글 달기 버튼을 누르는 분' where id = 35139;
 update posts set base_title = '이모지 형식의 말꼬리 만들기' where id = 35140;
 update posts set base_title = '🔥 중요 - 메일에 대해 알아둘 사항' where id = 35144;
 update posts set base_title = '🔥[제안] 버나크 커뮤니티 오픈을 1주일 정도 미루면 어떨까요?' where id = 35147;
 update posts set base_title = '사이드바 채널-폴더' where id = 35149;
 update posts set base_title = '사이드 바 채널 명 앞에 해시 대신에 버터 조각을 ㅎㅎ' where id = 35150;
 update posts set base_title = '이레 님 이 채널은 삭제해주세요' where id = 35153;
 update posts set base_title = '오 모바일 3.0이네요?' where id = 35156;
 update posts set base_title = '1' where id = 35168;
 update posts set base_title = '11' where id = 35180;
 update posts set base_title = '버나크 커뮤니티 대문 내용 ' where id = 35186;
 update posts set base_title = '[소개] #공지 채널 💁🏻‍' where id = 35188;
 update posts set base_title = '[소개] #체크인 💁🏻‍' where id = 35189;
 update posts set base_title = '[6월 넷째주 체크인 🏃🏻‍♀️]' where id = 35191;
 update posts set base_title = '[소개] #체크아웃 💁🏻‍' where id = 35192;
 update posts set base_title = '테스트 ' where id = 35193;
 update posts set base_title = '가운데 화면 스크롤이 알람 위로 보입니다! ' where id = 35194;
 update posts set base_title = '[6월 넷째주 체크아웃 🍰]' where id = 35195;
 update posts set base_title = '[소개] #아무말대잔치 💁🏻‍' where id = 35196;
 update posts set base_title = '[소개와 양식] #자기소개 💁🏻‍' where id = 35197;
 update posts set base_title = '크루인증을 거치지 않고 그룹에 가입하는 방법을 찾았어요 😅' where id = 35198;
 update posts set base_title = '6/22 항해일지' where id = 35199;
 update posts set base_title = 'ggg' where id = 35200;
 update posts set base_title = '글쓰기' where id = 35205;
 update posts set base_title = '테스트 ' where id = 35206;
 update posts set base_title = '테스트' where id = 35207;
 update posts set base_title = '1 테스트 ' where id = 35208;
 update posts set base_title = '링크 테스트 ' where id = 35209;
 update posts set base_title = '댓글 테스트 ' where id = 35210;
 update posts set base_title = '파일 첨부 테스트 ' where id = 35211;
 update posts set base_title = '버나크 공지 채널에 '가이드' 폴더를 추가했습니다. ' where id = 35215;
 update posts set base_title = '찬반투표 ' where id = 35222;
 update posts set base_title = '설문' where id = 35223;
 update posts set base_title = '안녕하세요. 버터나이프크루 체인입니다✨' where id = 35229;
 update posts set base_title = '여러분 굿즈, 좋아하세요? 💖' where id = 35230;
 update posts set base_title = '수요일에 비가 온다고 하는데요?' where id = 35231;
 update posts set base_title = '안녕하세요 버터나이프크루&빠띠의 씽입니다 🍊' where id = 35232;
 update posts set base_title = '글 참여자 ' where id = 35236;
 update posts set base_title = '체인님? chain님?' where id = 35279;
 update posts set base_title = '요즘 핫한 HEY' where id = 35280;
 update posts set base_title = '[긴급] 에디터의 이미지 첨부를 당분간 쓰지 말아주세요' where id = 35281;
 update posts set base_title = '그룹스 무료 플랜에서 채널 갯수 쿼터 혹은 유료 모델 논의' where id = 35288;
 update posts set base_title = '테크페미의 오예슬입니다 💚' where id = 35291;
 update posts set base_title = '한 회원이 그룹마다 부캐 만들기' where id = 35300;
 update posts set base_title = '이든쌤의 전지연입니다 !' where id = 35308;
 update posts set base_title = '3.0과 2.0의 경험 차이' where id = 35310;
 update posts set base_title = '아이스티(I-STI)의 수욘입니다👼🏽' where id = 35321;
 update posts set base_title = '소년 님이 공유해주신 디스코드' where id = 35323;
 update posts set base_title = '당신의 MBTI는? 👀' where id = 35328;
 update posts set base_title = 'TEDxSEOUL팀 연두입니다. ' where id = 35329;
 update posts set base_title = 'TEDxSeoul 유릴리 ' where id = 35330;
 update posts set base_title = '오오 버나크 자기소개 재밌는 분들! ' where id = 35331;
 update posts set base_title = '보슈팀의 공연화입니다.' where id = 35333;
 update posts set base_title = '인터브이의 최주연' where id = 35336;
 update posts set base_title = '6/25 항해일지' where id = 35339;
 update posts set base_title = '[소개] #슬기로운 회계생활 💁🏻‍' where id = 35340;
 update posts set base_title = '[공지] 2020 버터나이프크루 2기 회계 가이드 📗' where id = 35341;
 update posts set base_title = '📗 버터나이프크루 2기 회계 가이드' where id = 35342;
 update posts set base_title = '[공지] 첫번째 커뮤니티 미션, 같이 해볼까요?💪(~7/1)' where id = 35343;
 update posts set base_title = '[공지] 회계, 세무 Q&A를 위한 #슬기로운회계생활 오픈! 💌' where id = 35346;
 update posts set base_title = '테크페미의 김소희입니다.' where id = 35351;
 update posts set base_title = '[출범식]발표자료' where id = 35361;
 update posts set base_title = '[출범식]팀 소개 영상' where id = 35362;
 update posts set base_title = '[출범식]사진' where id = 35363;
 update posts set base_title = '당직제' where id = 35366;
 update posts set base_title = '🎯 3.1 일감' where id = 35369;
 update posts set base_title = '저장 테스트' where id = 35370;
 update posts set base_title = '버전 관리 정상 복구 선언' where id = 35373;
 update posts set base_title = '마티포포의 정유미입니다.' where id = 35376;
 update posts set base_title = '이든쌤의 이수민입니다!' where id = 35378;
 update posts set base_title = '이든쌤팀의 이혜진입니다!!' where id = 35379;
 update posts set base_title = '온라인 회의 ' where id = 35380;
 update posts set base_title = '페미리의 서예람입니다.' where id = 35388;
 update posts set base_title = '하하호호의 대빵입니다.' where id = 35389;
 update posts set base_title = '크루원 여러분, 저희 SNS 공유할까요! ' where id = 35390;
 update posts set base_title = '🌱 테크페미의 옥지혜입니다' where id = 35391;
 update posts set base_title = '업살롱의 김미영입니다.' where id = 35392;
 update posts set base_title = '통장사본 및 신분증 첨부 관련 질문입니다.' where id = 35395;
 update posts set base_title = '[6월 마지막주 체크인 🙌]' where id = 35401;
 update posts set base_title = '[6월 마지막주 체크아웃 ☕️]' where id = 35402;
 update posts set base_title = '<여성개발자컨퍼런스 2020 미리 설문>에 참여해 주세요!' where id = 35403;
 update posts set base_title = '저 방금 가입한 달리입니다.' where id = 35407;
 update posts set base_title = '회계와 컨퍼런스 관련 질문 드립니다.' where id = 35409;
 update posts set base_title = '하하호호 이현입니다.' where id = 35412;
 update posts set base_title = '링크 테스트' where id = 35413;
 update posts set base_title = '설문' where id = 35414;
 update posts set base_title = '🧑🏽‍💻테크페미의 예원입니다!' where id = 35416;
 update posts set base_title = '2.0과 3.0을 오가며 만나는 버그 ' where id = 35421;
 update posts set base_title = '(지겹지만) 당근마켓' where id = 35426;
 update posts set base_title = '비가 부슬부슬 오는군요.. 당신의 선택은? ' where id = 35427;
 update posts set base_title = '하하호호 하이입니다' where id = 35436;
 update posts set base_title = '뉴그룹스 채널 개수 제한을 풀까요? ' where id = 35437;
 update posts set base_title = '테스트' where id = 35455;
 update posts set base_title = '댓글' where id = 35456;
 update posts set base_title = '첨부파일 테스트 ' where id = 35462;
 update posts set base_title = '6/30 항해일지' where id = 35466;
 update posts set base_title = '긴박한집의 김민정입니다!' where id = 35470;
 update posts set base_title = '진짜 서울 ' where id = 35494;
 update posts set base_title = '그룹스 기능을 몰라서 못 쓰는 유저들' where id = 35499;
 update posts set base_title = '[제안] 게시물 팔로잉' where id = 35501;
 update posts set base_title = '마티포포 홍현진입니다:)' where id = 35502;
 update posts set base_title = '테크페미의 청설모입니다.' where id = 35507;
 update posts set base_title = '[공지] 프로필이 업그레이드 되었습니다! 👀' where id = 35508;
 update posts set base_title = '[제안] 공지 채널의 제목 포맷 잡기' where id = 35519;
 update posts set base_title = '페미니즘 뉴스레터 '사이'안내' where id = 35520;
 update posts set base_title = '1' where id = 35521;
 update posts set base_title = '2차 입금시기와 수정 예산안 관련 질문드려요' where id = 35523;
 update posts set base_title = '찬반투표' where id = 35524;
 update posts set base_title = '테스트' where id = 35525;
 update posts set base_title = '긴박한집-혜진' where id = 35532;
 update posts set base_title = '아무말대잔치 채널의 게시물 고정 정책' where id = 35541;
 update posts set base_title = '책 추천 하나, 장류진 <연수>' where id = 35543;
 update posts set base_title = '유튜버 싱라라 브이로그 x 업살롱 버나크 공식 첫 회의 현장' where id = 35544;
 update posts set base_title = '[제안] 게시글을 좀더 공동작업스럽게 만들기 1탄' where id = 35546;
 update posts set base_title = '슬회 채널 답변 속도와 커뮤니티 가드닝' where id = 35547;
 update posts set base_title = '[제안] 메일 알림을 뺄까요?' where id = 35548;
 update posts set base_title = '버터네 책방' where id = 35583;
 update posts set base_title = '버그' where id = 35586;
 update posts set base_title = '[소개] #버터꿀단지 💁🏻‍' where id = 35587;
 update posts set base_title = '[소개] #홍보게시판 💁🏻‍' where id = 35589;
 update posts set base_title = '미팅 준비 위키에서 목표에 대해' where id = 35590;
 update posts set base_title = 'test' where id = 35595;
 update posts set base_title = '[공지] 서로의 기여를 위한 채널을 만들었어요! 🙏' where id = 35597;
 update posts set base_title = '그룹의 서비스 형태 - 가입형 / 단독형' where id = 35605;
 update posts set base_title = '테크페미의 김문선입니다. ' where id = 35612;
 update posts set base_title = '회원가입과 그룹가입' where id = 35618;
 update posts set base_title = '2020 7월 4일 회의록(예시)' where id = 35620;
 update posts set base_title = '제1차 소식지제작모임 회의록 & 배열표' where id = 35638;
 update posts set base_title = '제2차 소식지제작모임 회의록' where id = 35639;
 update posts set base_title = '[7월 첫째주 체크인 🏄🏻‍♀️]' where id = 35641;
 update posts set base_title = '배열표(수정)' where id = 35645;
 update posts set base_title = '디지털 가든' where id = 35658;
 update posts set base_title = '지출 방식 문의드립니다.' where id = 35660;
 update posts set base_title = 'Of Digital Streams, Campfires and Gardens' where id = 35664;
 update posts set base_title = '[체크인🏄🏻‍♀️] 7월 첫째주 체크인' where id = 35670;
 update posts set base_title = '체크인, 체크아웃은 자유롭게 참여하면 되나요? ' where id = 35671;
 update posts set base_title = '혹시 저희 중간모임 날짜가 나왔나요? ' where id = 35672;
 update posts set base_title = '안전가옥의 최지혜입니다' where id = 35678;
 update posts set base_title = '[7월 첫째주 체크아웃 🌿]' where id = 35685;
 update posts set base_title = '[공지] 유스펀치 커뮤니티 매뉴얼' where id = 35688;
 update posts set base_title = 'discord' where id = 35714;
 update posts set base_title = '페미리의 팡세 입니다!' where id = 35716;
 update posts set base_title = 'I-STI의 예은입니다😃' where id = 35721;
 update posts set base_title = '코드포코리아 공적마스크 백서 위키' where id = 35722;
 update posts set base_title = '프로젝트 별 PL 정 과 부 && 후방 지원 ' where id = 35724;
 update posts set base_title = '🏖더위를 날려줄 ALL크루 출석체크 이벤트🏄🏻‍♀️' where id = 35732;
 update posts set base_title = '테크페미의 보니 입니다!' where id = 35735;
 update posts set base_title = '체크박스 배너가 상단에 있는 커뮤니티 feverbee (디스코스)' where id = 35741;
 update posts set base_title = 'How technology literally changes our brains' where id = 35749;
 update posts set base_title = '3.x 개선 아이디어' where id = 35773;
 update posts set base_title = '[IT 개발자와 일할 때 필요한 모든 개발지식] A to Z 자료 모음집 By 그랩' where id = 35774;
 update posts set base_title = '[세상읽기] 어디에서 사회를 배울 수 있을까? (여성신문, 함세정 인류학자)' where id = 35783;
 update posts set base_title = '참여예산 숙의 플랫폼 citizen budget (by ethelo)' where id = 35785;
 update posts set base_title = '버나크 운영진 빠띠(2.0)를 3.0으로 전환할까요? ' where id = 35789;
 update posts set base_title = '뉴스/정보는 누군가의 레고가 될 순 없을까' where id = 35792;
 update posts set base_title = '[체크아웃🧃] 7월 첫째주 체크아웃' where id = 35793;
 update posts set base_title = '전국의 냥팬들과 공유하고 싶은 것 ' where id = 35795;
 update posts set base_title = '토요일 점심은 냉면인가 아닌가?' where id = 35798;
 update posts set base_title = '냉면 메뉴 설문 받겠습니다.' where id = 35799;
 update posts set base_title = '팩티 여러분 인사를 나눠봐요.' where id = 35802;
 update posts set base_title = '설문 올려봅니다' where id = 35811;
 update posts set base_title = '200711) 뉴스타파 리영희 홀에서...' where id = 35812;
 update posts set base_title = '아이언맨은 안죽엇어요 ' where id = 35819;
 update posts set base_title = '7조' where id = 35820;
 update posts set base_title = '조 과제 역할 분배입니다' where id = 35821;
 update posts set base_title = 'FBI' where id = 35822;
 update posts set base_title = '익명투표' where id = 35823;
 update posts set base_title = '추천하는 드라마' where id = 35824;
 update posts set base_title = '예시로 보여드리는 [유스펀치] 커뮤니티입니다! 🙌' where id = 35825;
 update posts set base_title = '투표 테스트' where id = 35826;
 update posts set base_title = '비바리움' where id = 35827;
 update posts set base_title = '[JTBC 팩트체크] 차별금지법, 외국인에게 투표권 주는 법?' where id = 35828;
 update posts set base_title = '탕수육 부먹 찍먹' where id = 35829;
 update posts set base_title = '스스스' where id = 35830;
 update posts set base_title = '용용님' where id = 35831;
 update posts set base_title = '팩토리 조에서 선정한 번역할 영상입니다!' where id = 35841;
 update posts set base_title = '[7월 둘째주 체크인 🌿] 삶의 질 상승, 아이템 나누기 :) ' where id = 35846;
 update posts set base_title = '[7월 둘째주 로그아웃] 퇴근시간 🚃 ' where id = 35848;
 update posts set base_title = '[스터디 도서] 초연결사회와 보통사람의 시대' where id = 35851;
 update posts set base_title = '[체크인🍯 ] 7월 둘째주 체크인' where id = 35852;
 update posts set base_title = '위티 팀 채널이 '공지' 채널로 설정' where id = 35853;
 update posts set base_title = '📚 동네책방 좋아하세요? ' where id = 35863;
 update posts set base_title = '안전가옥의 호벤입니다!' where id = 35869;
 update posts set base_title = '책. 과학이 만드는 민주주의 ' where id = 35871;
 update posts set base_title = '안전가옥의 비구입니다.' where id = 35874;
 update posts set base_title = '안녕하세요. 안전가옥팀의 박보람입니다.' where id = 35875;
 update posts set base_title = '모두가 함께할 멘토링을 제안해주세요! 📝' where id = 35880;
 update posts set base_title = '조직심리학 교재' where id = 35882;
 update posts set base_title = '🗓데모데이 일정 공유: 8/29(토) 오후 2시-5시 ' where id = 35883;
 update posts set base_title = '캘린더' where id = 35886;
 update posts set base_title = '글 참여자' where id = 35890;
 update posts set base_title = '다른 그룹으로 이동' where id = 35891;
 update posts set base_title = '그룹에 가입을 권유하기' where id = 35892;
 update posts set base_title = '[공지] 중간모임 아이디어를 나누어 주세요!  ' where id = 35893;
 update posts set base_title = '라벨 ' where id = 35895;
 update posts set base_title = '폴더 항목 너비값 고정하기 ' where id = 35906;
 update posts set base_title = '“사실 이건 인공지능이 더 잘할 수 있는 일이거든요”' where id = 35908;
 update posts set base_title = '오픈패스의 “서클” (커뮤니티 서비스)' where id = 35911;
 update posts set base_title = '안전가옥의 사월' where id = 35912;
 update posts set base_title = '어제 강의 기획 회의에서 언급된 책들' where id = 35913;
 update posts set base_title = '게시판 요청합니다!' where id = 35919;
 update posts set base_title = '여기 너무너무 예쁜 그립톡/스티커 좀 봐주세요🥰' where id = 35920;
 update posts set base_title = '청소년 공익활동가들의 커뮤니티를 만듭니다. ' where id = 35921;
 update posts set base_title = '올해의 라인업은?' where id = 35922;
 update posts set base_title = '경기도 '프로젝트 젠더공감 2030' 팀 모집(~7.17 금요일 마감)' where id = 35924;
 update posts set base_title = '[리모트 워크 기업 ‘오토매틱’ 사례]  8시간 자리만 지키면 무슨 소용? 리모트 워크 핵심은 효율적 업무 진행' where id = 35925;
 update posts set base_title = '읽을거리 - 첫 번째 고객을 유치하는 방법 (feat. B2B 기업)' where id = 35937;
 update posts set base_title = '사회적경제지원센터 강의자료 개요' where id = 35940;
 update posts set base_title = '강의 자료 목차 - 포스트코로나 시대의 신뢰와 협력' where id = 35941;
 update posts set base_title = '[중요] 프로젝트 채널 개설 요청' where id = 35948;
 update posts set base_title = '채널개설을 원하는 팀 등에 관한 것 공유 및 피드백 요청드려요' where id = 35949;
 update posts set base_title = '운영진이 제안하는 ‘콘텐츠 확산 완전 기초 편'' where id = 35950;
 update posts set base_title = '인스타그램 팔로우, 좋아요 부탁드려요!' where id = 35954;
 update posts set base_title = '안전가옥의 수지입니다' where id = 35964;
 update posts set base_title = '[체크아웃👀] 7월 둘째주 체크아웃' where id = 35965;
 update posts set base_title = '질의응답 ' where id = 35967;
 update posts set base_title = '멘토링 제안 정리 by 버나크 ' where id = 35968;
 update posts set base_title = '3.2 일감' where id = 35969;
 update posts set base_title = '[공지] 멘토링을 제안해주세요! 👩🏻‍🎓' where id = 35971;
 update posts set base_title = '2019 버나크 사이트 관련 정보' where id = 35975;