 Post.find(22999).update_columns(base_title: "[마이크임팩트] 2018 서울 소셜 컨퍼런스")
 Post.find(27061).update_columns(base_title: "밸류가든 특강 요청")
 Post.find(30398).update_columns(base_title: "홈페이지 메인 1번 2번 3번 중 어떤게 마음에 드시나요?  @all 어떤 페이지로 구성하면 협업 문의가 많이 들어올까요?  댓글로 코멘트 부탁드려요.    * 목업에...")
 Post.find(30705).update_columns(base_title: "2019.09.26 운영팀 정기 회의록입니다. (첨부파일)")
 Post.find(31098).update_columns(base_title: "2019-10-16 베스툴 외부 회의록")
 Post.find(31182).update_columns(base_title: "2019.10.30 스탠드업 미팅")
 Post.find(31791).update_columns(base_title: "스프린트 1 ")
 Post.find(31859).update_columns(base_title: "스프린트 2.5")
 Post.find(31894).update_columns(base_title: "스프린트 2")
 Post.find(32025).update_columns(base_title: "스프린트 3")
 Post.find(32959).update_columns(base_title: "2020년 2월 20일 목요일 금귤 항해일지")
 Post.find(34926).update_columns(base_title: "테스트")
 Post.find(34928).update_columns(base_title: "체크인")
 Post.find(34929).update_columns(base_title: "테스트 ")
 Post.find(34930).update_columns(base_title: "글")
 Post.find(34931).update_columns(base_title: "페이징 테스트 1")
 Post.find(34932).update_columns(base_title: "페이징 테스트 2")
 Post.find(34933).update_columns(base_title: "페이징 테스트 3")
 Post.find(34934).update_columns(base_title: "페이징 테스트 4")
 Post.find(34935).update_columns(base_title: "페이징 테스트 5")
 Post.find(34936).update_columns(base_title: "페이징 테스트 6")
 Post.find(34937).update_columns(base_title: "페이징 테스트 7")
 Post.find(34938).update_columns(base_title: "페이징 테스트 8")
 Post.find(34939).update_columns(base_title: "페이징 테스트 9")
 Post.find(34940).update_columns(base_title: "도배 방지 위원회")
 Post.find(34948).update_columns(base_title: "[공지] 유스펀치 오거나이저를 찾습니다! 👀")
 Post.find(34949).update_columns(base_title: "[공지] 커뮤니티 멤버 이름을 공모합니다! ✍️")
 Post.find(34950).update_columns(base_title: "[인사] 첫 인사를 나눠보아요! 😁")
 Post.find(34951).update_columns(base_title: "[체크아웃🌈] 6월 둘째주 체크아웃")
 Post.find(34952).update_columns(base_title: "[체크인👋] 6월 둘째주 체크인")
 Post.find(34973).update_columns(base_title: "그룹스 3.0인가요?")
 Post.find(34985).update_columns(base_title: "쓰레기덕질 컵보증금제 축하파티")
 Post.find(34986).update_columns(base_title: "여름에 휴가는 어디로?")
 Post.find(34987).update_columns(base_title: "사진은 어떻게 올리는 걸까?")
 Post.find(34988).update_columns(base_title: "뉴그룹스 시작을 축하")
 Post.find(34990).update_columns(base_title: "테스트 ")
 Post.find(34992).update_columns(base_title: "📌그룹 주제 편집하고 나니 미분류 채널이 생성되었습니다.")
 Post.find(34993).update_columns(base_title: "행동강령")
 Post.find(34995).update_columns(base_title: "그룹스3.0 버그")
 Post.find(34996).update_columns(base_title: "빠띠에 오기 전")
 Post.find(35000).update_columns(base_title: "항해일지를 여기서 써보면?")
 Post.find(35001).update_columns(base_title: "글목록에 N의 공격!")
 Post.find(35002).update_columns(base_title: "3요소")
 Post.find(35003).update_columns(base_title: "목록으로 돌아가기 버튼")
 Post.find(35005).update_columns(base_title: "게시글 삭제가 되는지 확인용")
 Post.find(35006).update_columns(base_title: "에디터에서 새롭게 발견한 사실! ")
 Post.find(35007).update_columns(base_title: "저는 폴더도 만들어봤어요")
 Post.find(35008).update_columns(base_title: "p.d.a")
 Post.find(35009).update_columns(base_title: "새친구 알람")
 Post.find(35010).update_columns(base_title: "달리님 회의의 시간입니다 회고")
 Post.find(35015).update_columns(base_title: "일감")
 Post.find(35017).update_columns(base_title: "그룹 멤버 전체에 알리는 글")
 Post.find(35022).update_columns(base_title: "댓글에도 새 댓글 표시 달기")
 Post.find(35028).update_columns(base_title: "그룹과 그룹 사이 거리")
 Post.find(35036).update_columns(base_title: "2020년 6월 16일 항해일지")
 Post.find(35040).update_columns(base_title: "잡담. 개발자 커뮤니티에서 로그(일지) 엿보기")
 Post.find(35047).update_columns(base_title: "모바일 3.0 목업")
 Post.find(35050).update_columns(base_title: "언젠가 게스트를...")
 Post.find(35055).update_columns(base_title: "글과 댓글의 게시시간에 대한 초간단 개선 의견")
 Post.find(35060).update_columns(base_title: "공지한 글을 확인하는 것")
 Post.find(35104).update_columns(base_title: "로그인 및 가입 만들기")
 Post.find(35107).update_columns(base_title: "유스펀치 2.0")
 Post.find(35111).update_columns(base_title: "6/18-19 항해일지 ")
 Post.find(35112).update_columns(base_title: "3.0의 폰트사이즈나 목록의 위아래 길이를 조금 줄여보면 어떨까요? ")
 Post.find(35113).update_columns(base_title: "에디터 내 enter 키를 눌렀을 경우 다음 줄 ")
 Post.find(35125).update_columns(base_title: "마지막에 접속한 채널을 기억하기")
 Post.find(35127).update_columns(base_title: "새 글을 주기적으로 확인하기")
 Post.find(35128).update_columns(base_title: "글 쓰기 테스트 1")
 Post.find(35129).update_columns(base_title: "사진, 파일 첨부 테스트")
 Post.find(35130).update_columns(base_title: "찬반투표 테스트")
 Post.find(35131).update_columns(base_title: "설문 테스트")
 Post.find(35134).update_columns(base_title: "그룹의 채널 개설 권한")
 Post.find(35135).update_columns(base_title: "레셈님과 디자인 관련 회의")
 Post.find(35136).update_columns(base_title: "대문위키에 들어가는 이미지 ")
 Post.find(35137).update_columns(base_title: "이미지 업로드 테스트 ")
 Post.find(35138).update_columns(base_title: "대문위키에 들어가는 이미지 디자인 ")
 Post.find(35139).update_columns(base_title: "3.0에서 공감을 누르고 싶었는데 댓글 달기 버튼을 누르는 분")
 Post.find(35140).update_columns(base_title: "이모지 형식의 말꼬리 만들기")
 Post.find(35144).update_columns(base_title: "🔥 중요 - 메일에 대해 알아둘 사항")
 Post.find(35147).update_columns(base_title: "🔥[제안] 버나크 커뮤니티 오픈을 1주일 정도 미루면 어떨까요?")
 Post.find(35149).update_columns(base_title: "사이드바 채널-폴더")
 Post.find(35150).update_columns(base_title: "사이드 바 채널 명 앞에 해시 대신에 버터 조각을 ㅎㅎ")
 Post.find(35153).update_columns(base_title: "이레 님 이 채널은 삭제해주세요")
 Post.find(35156).update_columns(base_title: "오 모바일 3.0이네요?")
 Post.find(35168).update_columns(base_title: "1")
 Post.find(35180).update_columns(base_title: "11")
 Post.find(35186).update_columns(base_title: "버나크 커뮤니티 대문 내용 ")
 Post.find(35188).update_columns(base_title: "[소개] #공지 채널 💁🏻‍")
 Post.find(35189).update_columns(base_title: "[소개] #체크인 💁🏻‍")
 Post.find(35191).update_columns(base_title: "[6월 넷째주 체크인 🏃🏻‍♀️]")
 Post.find(35192).update_columns(base_title: "[소개] #체크아웃 💁🏻‍")
 Post.find(35193).update_columns(base_title: "테스트 ")
 Post.find(35194).update_columns(base_title: "가운데 화면 스크롤이 알람 위로 보입니다! ")
 Post.find(35195).update_columns(base_title: "[6월 넷째주 체크아웃 🍰]")
 Post.find(35196).update_columns(base_title: "[소개] #아무말대잔치 💁🏻‍")
 Post.find(35197).update_columns(base_title: "[소개와 양식] #자기소개 💁🏻‍")
 Post.find(35198).update_columns(base_title: "크루인증을 거치지 않고 그룹에 가입하는 방법을 찾았어요 😅")
 Post.find(35199).update_columns(base_title: "6/22 항해일지")
 Post.find(35200).update_columns(base_title: "ggg")
 Post.find(35205).update_columns(base_title: "글쓰기")
 Post.find(35206).update_columns(base_title: "테스트 ")
 Post.find(35207).update_columns(base_title: "테스트")
 Post.find(35208).update_columns(base_title: "1 테스트 ")
 Post.find(35209).update_columns(base_title: "링크 테스트 ")
 Post.find(35210).update_columns(base_title: "댓글 테스트 ")
 Post.find(35211).update_columns(base_title: "파일 첨부 테스트 ")
 Post.find(35215).update_columns(base_title: "버나크 공지 채널에 '가이드' 폴더를 추가했습니다. ")
 Post.find(35222).update_columns(base_title: "찬반투표 ")
 Post.find(35223).update_columns(base_title: "설문")
 Post.find(35229).update_columns(base_title: "안녕하세요. 버터나이프크루 체인입니다✨")
 Post.find(35230).update_columns(base_title: "여러분 굿즈, 좋아하세요? 💖")
 Post.find(35231).update_columns(base_title: "수요일에 비가 온다고 하는데요?")
 Post.find(35232).update_columns(base_title: "안녕하세요 버터나이프크루&빠띠의 씽입니다 🍊")
 Post.find(35236).update_columns(base_title: "글 참여자 ")
 Post.find(35279).update_columns(base_title: "체인님? chain님?")
 Post.find(35280).update_columns(base_title: "요즘 핫한 HEY")
 Post.find(35281).update_columns(base_title: "[긴급] 에디터의 이미지 첨부를 당분간 쓰지 말아주세요")
 Post.find(35288).update_columns(base_title: "그룹스 무료 플랜에서 채널 갯수 쿼터 혹은 유료 모델 논의")
 Post.find(35291).update_columns(base_title: "테크페미의 오예슬입니다 💚")
 Post.find(35300).update_columns(base_title: "한 회원이 그룹마다 부캐 만들기")
 Post.find(35308).update_columns(base_title: "이든쌤의 전지연입니다 !")
 Post.find(35310).update_columns(base_title: "3.0과 2.0의 경험 차이")
 Post.find(35321).update_columns(base_title: "아이스티(I-STI)의 수욘입니다👼🏽")
 Post.find(35323).update_columns(base_title: "소년 님이 공유해주신 디스코드")
 Post.find(35328).update_columns(base_title: "당신의 MBTI는? 👀")
 Post.find(35329).update_columns(base_title: "TEDxSEOUL팀 연두입니다. ")
 Post.find(35330).update_columns(base_title: "TEDxSeoul 유릴리 ")
 Post.find(35331).update_columns(base_title: "오오 버나크 자기소개 재밌는 분들! ")
 Post.find(35333).update_columns(base_title: "보슈팀의 공연화입니다.")
 Post.find(35336).update_columns(base_title: "인터브이의 최주연")
 Post.find(35339).update_columns(base_title: "6/25 항해일지")
 Post.find(35340).update_columns(base_title: "[소개] #슬기로운 회계생활 💁🏻‍")
 Post.find(35341).update_columns(base_title: "[공지] 2020 버터나이프크루 2기 회계 가이드 📗")
 Post.find(35342).update_columns(base_title: "📗 버터나이프크루 2기 회계 가이드")
 Post.find(35343).update_columns(base_title: "[공지] 첫번째 커뮤니티 미션, 같이 해볼까요?💪(~7/1)")
 Post.find(35346).update_columns(base_title: "[공지] 회계, 세무 Q&A를 위한 #슬기로운회계생활 오픈! 💌")
 Post.find(35351).update_columns(base_title: "테크페미의 김소희입니다.")
 Post.find(35361).update_columns(base_title: "[출범식]발표자료")
 Post.find(35362).update_columns(base_title: "[출범식]팀 소개 영상")
 Post.find(35363).update_columns(base_title: "[출범식]사진")
 Post.find(35366).update_columns(base_title: "당직제")
 Post.find(35369).update_columns(base_title: "🎯 3.1 일감")
 Post.find(35370).update_columns(base_title: "저장 테스트")
 Post.find(35373).update_columns(base_title: "버전 관리 정상 복구 선언")
 Post.find(35376).update_columns(base_title: "마티포포의 정유미입니다.")
 Post.find(35378).update_columns(base_title: "이든쌤의 이수민입니다!")
 Post.find(35379).update_columns(base_title: "이든쌤팀의 이혜진입니다!!")
 Post.find(35380).update_columns(base_title: "온라인 회의 ")
 Post.find(35388).update_columns(base_title: "페미리의 서예람입니다.")
 Post.find(35389).update_columns(base_title: "하하호호의 대빵입니다.")
 Post.find(35390).update_columns(base_title: "크루원 여러분, 저희 SNS 공유할까요! ")
 Post.find(35391).update_columns(base_title: "🌱 테크페미의 옥지혜입니다")
 Post.find(35392).update_columns(base_title: "업살롱의 김미영입니다.")
 Post.find(35395).update_columns(base_title: "통장사본 및 신분증 첨부 관련 질문입니다.")
 Post.find(35401).update_columns(base_title: "[6월 마지막주 체크인 🙌]")
 Post.find(35402).update_columns(base_title: "[6월 마지막주 체크아웃 ☕️]")
 Post.find(35403).update_columns(base_title: "<여성개발자컨퍼런스 2020 미리 설문>에 참여해 주세요!")
 Post.find(35407).update_columns(base_title: "저 방금 가입한 달리입니다.")
 Post.find(35409).update_columns(base_title: "회계와 컨퍼런스 관련 질문 드립니다.")
 Post.find(35412).update_columns(base_title: "하하호호 이현입니다.")
 Post.find(35413).update_columns(base_title: "링크 테스트")
 Post.find(35414).update_columns(base_title: "설문")
 Post.find(35416).update_columns(base_title: "🧑🏽‍💻테크페미의 예원입니다!")
 Post.find(35421).update_columns(base_title: "2.0과 3.0을 오가며 만나는 버그 ")
 Post.find(35426).update_columns(base_title: "(지겹지만) 당근마켓")
 Post.find(35427).update_columns(base_title: "비가 부슬부슬 오는군요.. 당신의 선택은? ")
 Post.find(35436).update_columns(base_title: "하하호호 하이입니다")
 Post.find(35437).update_columns(base_title: "뉴그룹스 채널 개수 제한을 풀까요? ")
 Post.find(35455).update_columns(base_title: "테스트")
 Post.find(35456).update_columns(base_title: "댓글")
 Post.find(35462).update_columns(base_title: "첨부파일 테스트 ")
 Post.find(35466).update_columns(base_title: "6/30 항해일지")
 Post.find(35470).update_columns(base_title: "긴박한집의 김민정입니다!")
 Post.find(35494).update_columns(base_title: "진짜 서울 ")
 Post.find(35499).update_columns(base_title: "그룹스 기능을 몰라서 못 쓰는 유저들")
 Post.find(35501).update_columns(base_title: "[제안] 게시물 팔로잉")
 Post.find(35502).update_columns(base_title: "마티포포 홍현진입니다:)")
 Post.find(35507).update_columns(base_title: "테크페미의 청설모입니다.")
 Post.find(35508).update_columns(base_title: "[공지] 프로필이 업그레이드 되었습니다! 👀")
 Post.find(35519).update_columns(base_title: "[제안] 공지 채널의 제목 포맷 잡기")
 Post.find(35520).update_columns(base_title: "페미니즘 뉴스레터 '사이'안내")
 Post.find(35521).update_columns(base_title: "1")
 Post.find(35523).update_columns(base_title: "2차 입금시기와 수정 예산안 관련 질문드려요")
 Post.find(35524).update_columns(base_title: "찬반투표")
 Post.find(35525).update_columns(base_title: "테스트")
 Post.find(35532).update_columns(base_title: "긴박한집-혜진")
 Post.find(35541).update_columns(base_title: "아무말대잔치 채널의 게시물 고정 정책")
 Post.find(35543).update_columns(base_title: "책 추천 하나, 장류진 <연수>")
 Post.find(35544).update_columns(base_title: "유튜버 싱라라 브이로그 x 업살롱 버나크 공식 첫 회의 현장")
 Post.find(35546).update_columns(base_title: "[제안] 게시글을 좀더 공동작업스럽게 만들기 1탄")
 Post.find(35547).update_columns(base_title: "슬회 채널 답변 속도와 커뮤니티 가드닝")
 Post.find(35548).update_columns(base_title: "[제안] 메일 알림을 뺄까요?")
 Post.find(35583).update_columns(base_title: "버터네 책방")
 Post.find(35586).update_columns(base_title: "버그")
 Post.find(35587).update_columns(base_title: "[소개] #버터꿀단지 💁🏻‍")
 Post.find(35589).update_columns(base_title: "[소개] #홍보게시판 💁🏻‍")
 Post.find(35590).update_columns(base_title: "미팅 준비 위키에서 목표에 대해")
 Post.find(35595).update_columns(base_title: "test")
 Post.find(35597).update_columns(base_title: "[공지] 서로의 기여를 위한 채널을 만들었어요! 🙏")
 Post.find(35605).update_columns(base_title: "그룹의 서비스 형태 - 가입형 / 단독형")
 Post.find(35612).update_columns(base_title: "테크페미의 김문선입니다. ")
 Post.find(35618).update_columns(base_title: "회원가입과 그룹가입")
 Post.find(35620).update_columns(base_title: "2020 7월 4일 회의록(예시)")
 Post.find(35638).update_columns(base_title: "제1차 소식지제작모임 회의록 & 배열표")
 Post.find(35639).update_columns(base_title: "제2차 소식지제작모임 회의록")
 Post.find(35641).update_columns(base_title: "[7월 첫째주 체크인 🏄🏻‍♀️]")
 Post.find(35645).update_columns(base_title: "배열표(수정)")
 Post.find(35658).update_columns(base_title: "디지털 가든")
 Post.find(35660).update_columns(base_title: "지출 방식 문의드립니다.")
 Post.find(35664).update_columns(base_title: "Of Digital Streams, Campfires and Gardens")
 Post.find(35670).update_columns(base_title: "[체크인🏄🏻‍♀️] 7월 첫째주 체크인")
 Post.find(35671).update_columns(base_title: "체크인, 체크아웃은 자유롭게 참여하면 되나요? ")
 Post.find(35672).update_columns(base_title: "혹시 저희 중간모임 날짜가 나왔나요? ")
 Post.find(35678).update_columns(base_title: "안전가옥의 최지혜입니다")
 Post.find(35685).update_columns(base_title: "[7월 첫째주 체크아웃 🌿]")
 Post.find(35688).update_columns(base_title: "[공지] 유스펀치 커뮤니티 매뉴얼")
 Post.find(35714).update_columns(base_title: "discord")
 Post.find(35716).update_columns(base_title: "페미리의 팡세 입니다!")
 Post.find(35721).update_columns(base_title: "I-STI의 예은입니다😃")
 Post.find(35722).update_columns(base_title: "코드포코리아 공적마스크 백서 위키")
 Post.find(35724).update_columns(base_title: "프로젝트 별 PL 정 과 부 && 후방 지원 ")
 Post.find(35732).update_columns(base_title: "🏖더위를 날려줄 ALL크루 출석체크 이벤트🏄🏻‍♀️")
 Post.find(35735).update_columns(base_title: "테크페미의 보니 입니다!")
 Post.find(35741).update_columns(base_title: "체크박스 배너가 상단에 있는 커뮤니티 feverbee (디스코스)")
 Post.find(35749).update_columns(base_title: "How technology literally changes our brains")
 Post.find(35773).update_columns(base_title: "3.x 개선 아이디어")
 Post.find(35774).update_columns(base_title: "[IT 개발자와 일할 때 필요한 모든 개발지식] A to Z 자료 모음집 By 그랩")
 Post.find(35783).update_columns(base_title: "[세상읽기] 어디에서 사회를 배울 수 있을까? (여성신문, 함세정 인류학자)")
 Post.find(35785).update_columns(base_title: "참여예산 숙의 플랫폼 citizen budget (by ethelo)")
 Post.find(35789).update_columns(base_title: "버나크 운영진 빠띠(2.0)를 3.0으로 전환할까요? ")
 Post.find(35792).update_columns(base_title: "뉴스/정보는 누군가의 레고가 될 순 없을까")
 Post.find(35793).update_columns(base_title: "[체크아웃🧃] 7월 첫째주 체크아웃")
 Post.find(35795).update_columns(base_title: "전국의 냥팬들과 공유하고 싶은 것 ")
 Post.find(35798).update_columns(base_title: "토요일 점심은 냉면인가 아닌가?")
 Post.find(35799).update_columns(base_title: "냉면 메뉴 설문 받겠습니다.")
 Post.find(35802).update_columns(base_title: "팩티 여러분 인사를 나눠봐요.")
 Post.find(35811).update_columns(base_title: "설문 올려봅니다")
 Post.find(35812).update_columns(base_title: "200711) 뉴스타파 리영희 홀에서...")
 Post.find(35819).update_columns(base_title: "아이언맨은 안죽엇어요 ")
 Post.find(35820).update_columns(base_title: "7조")
 Post.find(35821).update_columns(base_title: "조 과제 역할 분배입니다")
 Post.find(35822).update_columns(base_title: "FBI")
 Post.find(35823).update_columns(base_title: "익명투표")
 Post.find(35824).update_columns(base_title: "추천하는 드라마")
 Post.find(35825).update_columns(base_title: "예시로 보여드리는 [유스펀치] 커뮤니티입니다! 🙌")
 Post.find(35826).update_columns(base_title: "투표 테스트")
 Post.find(35827).update_columns(base_title: "비바리움")
 Post.find(35828).update_columns(base_title: "[JTBC 팩트체크] 차별금지법, 외국인에게 투표권 주는 법?")
 Post.find(35829).update_columns(base_title: "탕수육 부먹 찍먹")
 Post.find(35830).update_columns(base_title: "스스스")
 Post.find(35831).update_columns(base_title: "용용님")
 Post.find(35841).update_columns(base_title: "팩토리 조에서 선정한 번역할 영상입니다!")
 Post.find(35846).update_columns(base_title: "[7월 둘째주 체크인 🌿] 삶의 질 상승, 아이템 나누기 :) ")
 Post.find(35848).update_columns(base_title: "[7월 둘째주 로그아웃] 퇴근시간 🚃 ")
 Post.find(35851).update_columns(base_title: "[스터디 도서] 초연결사회와 보통사람의 시대")
 Post.find(35852).update_columns(base_title: "[체크인🍯 ] 7월 둘째주 체크인")
 Post.find(35853).update_columns(base_title: "위티 팀 채널이 '공지' 채널로 설정")
 Post.find(35863).update_columns(base_title: "📚 동네책방 좋아하세요? ")
 Post.find(35869).update_columns(base_title: "안전가옥의 호벤입니다!")
 Post.find(35871).update_columns(base_title: "책. 과학이 만드는 민주주의 ")
 Post.find(35874).update_columns(base_title: "안전가옥의 비구입니다.")
 Post.find(35875).update_columns(base_title: "안녕하세요. 안전가옥팀의 박보람입니다.")
 Post.find(35880).update_columns(base_title: "모두가 함께할 멘토링을 제안해주세요! 📝")
 Post.find(35882).update_columns(base_title: "조직심리학 교재")
 Post.find(35883).update_columns(base_title: "🗓데모데이 일정 공유: 8/29(토) 오후 2시-5시 ")
 Post.find(35886).update_columns(base_title: "캘린더")
 Post.find(35890).update_columns(base_title: "글 참여자")
 Post.find(35891).update_columns(base_title: "다른 그룹으로 이동")
 Post.find(35892).update_columns(base_title: "그룹에 가입을 권유하기")
 Post.find(35893).update_columns(base_title: "[공지] 중간모임 아이디어를 나누어 주세요!  ")
 Post.find(35895).update_columns(base_title: "라벨 ")
 Post.find(35906).update_columns(base_title: "폴더 항목 너비값 고정하기 ")
 Post.find(35908).update_columns(base_title: "“사실 이건 인공지능이 더 잘할 수 있는 일이거든요”")
 Post.find(35911).update_columns(base_title: "오픈패스의 “서클” (커뮤니티 서비스)")
 Post.find(35912).update_columns(base_title: "안전가옥의 사월")
 Post.find(35913).update_columns(base_title: "어제 강의 기획 회의에서 언급된 책들")
 Post.find(35919).update_columns(base_title: "게시판 요청합니다!")
 Post.find(35920).update_columns(base_title: "여기 너무너무 예쁜 그립톡/스티커 좀 봐주세요🥰")
 Post.find(35921).update_columns(base_title: "청소년 공익활동가들의 커뮤니티를 만듭니다. ")
 Post.find(35922).update_columns(base_title: "올해의 라인업은?")
 Post.find(35924).update_columns(base_title: "경기도 '프로젝트 젠더공감 2030' 팀 모집(~7.17 금요일 마감)")
 Post.find(35925).update_columns(base_title: "[리모트 워크 기업 ‘오토매틱’ 사례]  8시간 자리만 지키면 무슨 소용? 리모트 워크 핵심은 효율적 업무 진행")
 Post.find(35937).update_columns(base_title: "읽을거리 - 첫 번째 고객을 유치하는 방법 (feat. B2B 기업)")
 Post.find(35940).update_columns(base_title: "사회적경제지원센터 강의자료 개요")
 Post.find(35941).update_columns(base_title: "강의 자료 목차 - 포스트코로나 시대의 신뢰와 협력")
 Post.find(35948).update_columns(base_title: "[중요] 프로젝트 채널 개설 요청")
 Post.find(35949).update_columns(base_title: "채널개설을 원하는 팀 등에 관한 것 공유 및 피드백 요청드려요")
 Post.find(35950).update_columns(base_title: "운영진이 제안하는 ‘콘텐츠 확산 완전 기초 편'")
 Post.find(35954).update_columns(base_title: "인스타그램 팔로우, 좋아요 부탁드려요!")
 Post.find(35964).update_columns(base_title: "안전가옥의 수지입니다")
 Post.find(35965).update_columns(base_title: "[체크아웃👀] 7월 둘째주 체크아웃")
 Post.find(35967).update_columns(base_title: "질의응답 ")
 Post.find(35968).update_columns(base_title: "멘토링 제안 정리 by 버나크 ")
 Post.find(35969).update_columns(base_title: "3.2 일감")
 Post.find(35971).update_columns(base_title: "[공지] 멘토링을 제안해주세요! 👩🏻‍🎓")
 Post.find(35975).update_columns(base_title: "2019 버나크 사이트 관련 정보")